package com.kanmenzhu.system.security.entity;

// Generated 2013-5-29 22:11:15 by Hibernate Tools 3.4.0.CR1

/**
 * LuRoleUser generated by hbm2java
 */
public class LuRoleUser implements java.io.Serializable {

	private Integer id;
	private int uid;
	private int rid;

	public LuRoleUser() {
	}

	public LuRoleUser(int uid, int rid) {
		this.uid = uid;
		this.rid = rid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

}
