package com.kanmenzhu.system.security.entity;

import com.kanmenzhu.bean.BaseBean;

// Generated 2013-5-29 22:00:52 by Hibernate Tools 3.4.0.CR1

/**
 * LuRole generated by hbm2java
 */
public class LuRole  extends BaseBean {

	private String name;
	private Integer deltag;
	private String type;
	private Integer parentId;
	private String memo;
	
	/** 角色：文教局 */
	public static String MANAGER = "MANAGER";
	/** 角色：供应商 */
	public static String SUPPLIER = "SUPPLIER";
	/** 角色：学校 */
	public static String SCHOOL = "SCHOOL";

	public LuRole() {
	}

	public LuRole(String name) {
		this.name = name;
	}

	public LuRole(String name, Integer deltag,String type, Integer parentId, String memo) {
		this.name = name;
		this.deltag = deltag;
		this.type = type;
		this.parentId = parentId;
		this.memo = memo;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDeltag() {
		return this.deltag;
	}

	public void setDeltag(Integer deltag) {
		this.deltag = deltag;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
