package com.kanmenzhu.system.security.entity;

import com.kanmenzhu.bean.BaseBean;

// Generated 2013-5-29 22:00:52 by Hibernate Tools 3.4.0.CR1

/**
 * LuRole generated by hbm2java
 */
public class LuRole  extends BaseBean {

	private Integer id;
	private String name;
	private Integer deltag;
	private Integer parentId;
	private String memo;

	public LuRole() {
	}

	public LuRole(String name) {
		this.name = name;
	}

	public LuRole(String name, Integer deltag, Integer parentId, String memo) {
		this.name = name;
		this.deltag = deltag;
		this.parentId = parentId;
		this.memo = memo;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDeltag() {
		return this.deltag;
	}

	public void setDeltag(Integer deltag) {
		this.deltag = deltag;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
